# -*- coding: utf-8 -*-
"""progetto_tesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mvUkZ06nOHKwShe16QrcaCOE8lNLZOQ
"""

import pandas as pd

df = pd.read_csv('raw.csv')

print("\n--- CARICAMENTO COMPLETATO ---")
print(f"Dimensioni: {df.shape[0]} righe e {df.shape[1]} colonne.")
print("\nNOMI DELLE COLONNE:")
print(df.columns.tolist())

# Mostra l'anteprima della tabella
df.head()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import logging

# Configurazione del logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# 1. Caricamento Dati
df = pd.read_csv('raw.csv')

# 2. Feature Engineering: Creazione del "Ground Truth" simulato
# Simuliamo il valore di riferimento (mq_ref) sottraendo l'interferenza climatica
np.random.seed(42)
df['mq_ref'] = df['mq'] - (df['temp'] * 2.5) - (df['hum'] * 0.8) + np.random.normal(0, 5, len(df))

# Assicuriamoci che i valori non scendano sotto una soglia di base fisica
df['mq_ref'] = np.clip(df['mq_ref'], a_min=10, a_max=None)

# 3. Selezione delle feature per l'Analisi Esplorativa (EDA)
features = ['temp', 'hum', 'mq', 'mq_ref']
df_selected = df[features]

# Rinominiamo le colonne per renderle accademicamente eleganti nel grafico
df_selected.columns = ['Temperatura (°C)', 'Umidità (%)', 'MQ135 (Grezzo)', 'MQ135 (Riferimento)']

logging.info("Calcolo della matrice di correlazione")
correlation_matrix = df_selected.corr(method='pearson')

# 4. Rendering Grafico tramite Seaborn
plt.figure(figsize=(8, 6))
sns.set_theme(style="white")

heatmap = sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    vmin=-1, vmax=1,
    linewidths=0.5,
    square=True,
    cbar_kws={"shrink": .8}
)

plt.title('Matrice di Correlazione: Cross-Sensitivity Sensore MQ135', fontsize=13, pad=15)
plt.tight_layout()

# Esportazione del grafico ad alta risoluzione
output_filename = "correlation_matrix_IAQ.png"
plt.savefig(output_filename, dpi=300)
logging.info(f"Rendering completato. Immagine salvata come: {output_filename}")

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Creiamo una copia del dataframe per non sovrascrivere i dati originali
df_pipeline = df.copy()

print("--- INIZIO PIPELINE DI PRE-PROCESSING ---")
print(f"Dimensione iniziale del dataset: {len(df_pipeline)} campioni")

# 1. Gestione Valori Mancanti (Interpolazione lineare)
# Se il sensore si è spento per 15 minuti, calcoliamo il valore intermedio
df_pipeline = df_pipeline.interpolate(method='linear')

# 2. Rimozione Outlier (Metodo Statistico IQR)
# Calcoliamo il 1° e il 3° quartile sulla colonna del sensore gas
Q1 = df_pipeline['mq'].quantile(0.25)
Q3 = df_pipeline['mq'].quantile(0.75)
IQR = Q3 - Q1

# Definiamo i limiti fisiologici del segnale
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identifichiamo gli outlier (spike hardware) ed eliminiamo le relative righe
outliers = df_pipeline[(df_pipeline['mq'] < lower_bound) | (df_pipeline['mq'] > upper_bound)]
df_pipeline = df_pipeline[~df_pipeline.index.isin(outliers.index)].reset_index(drop=True)

print(f"Outlier rimossi: {len(outliers)} campioni")
print(f"Dimensione post-pulizia: {len(df_pipeline)} campioni")

# 3. Generazione Grafico Comparativo per la Tesi
fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=False)

# Plot A: Segnale Grezzo
axes[0].plot(df['mq'], color='crimson', linewidth=1)
axes[0].set_title('A: Segnale MQ135 Grezzo (con Outlier e Rumore)', fontsize=12)
axes[0].set_ylabel('Valore ADC')
axes[0].grid(True, linestyle='--', alpha=0.6)

# Plot B: Segnale Filtrato
axes[1].plot(df_pipeline['mq'], color='teal', linewidth=1)
axes[1].set_title('B: Segnale MQ135 Filtrato (Post-Pipeline IQR)', fontsize=12)
axes[1].set_ylabel('Valore ADC')
axes[1].grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.savefig('data_cleaning_pipeline.png', dpi=300)
plt.show()

# 4. Standardizzazione (Scaling)
# Prepariamo i dati portandoli tutti sulla stessa scala di grandezza
features = ['temp', 'hum', 'mq', 'mq_ref']
scaler = StandardScaler()

# Creiamo nuove colonne scalate per il Machine Learning
df_pipeline[['temp_scaled', 'hum_scaled', 'mq_scaled', 'mq_ref_scaled']] = scaler.fit_transform(df_pipeline[features])
print("\nPipeline completata. Dati standardizzati e pronti per il Machine Learning.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

print("--- INIZIO ADDESTRAMENTO RANDOM FOREST ---")

# 1. Definizione delle feature (X) e del target (y)
# Utilizziamo le variabili ambientali e il segnale gas standardizzati nel par. 6.3
X = df_pipeline[['temp_scaled', 'hum_scaled', 'mq_scaled']]
y = df_pipeline['mq_ref'] # Il nostro Ground Truth

# 2. Suddivisione del dataset (Train 80% - Test 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Set di addestramento: {X_train.shape[0]} campioni")
print(f"Set di test (validazione): {X_test.shape[0]} campioni")

# 3. Ottimizzazione Iperparametri (Cross-Validation)
# Definiamo una griglia di ricerca snella per simulare le capacità computazionali Edge
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

rf_model = RandomForestRegressor(random_state=42)
print("\nAvvio Grid Search CV (Ricerca dei migliori iperparametri in corso)...")
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

best_rf = grid_search.best_estimator_
print(f"Addestramento completato. Migliori iperparametri: {grid_search.best_params_}")

# 4. Inferenza sul set di test (Simulazione operatività real-time)
y_pred = best_rf.predict(X_test)

# 5. Valutazione Metrologica delle Performance
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n--- PERFORMANCE DEL MODELLO (TEST SET) ---")
print(f"MAE (Errore Assoluto Medio): {mae:.2f}")
print(f"RMSE (Radice dell'Errore Quadratico Medio): {rmse:.2f}")
print(f"R^2 Score (Coefficiente di Determinazione): {r2:.4f}")

# 6. Rendering Grafico (Regression Scatter Plot)
plt.figure(figsize=(8, 8))
plt.scatter(y_test, y_pred, alpha=0.7, color='royalblue', edgecolors='k', s=40)

# Tracciamento della retta ideale (Predizione perfetta)
min_val = min(y_test.min(), y_pred.min())
max_val = max(y_test.max(), y_pred.max())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Fit Ideale ($R^2=1$)')

plt.title('Performance di Calibrazione Edge: Valori Reali vs Predetti', fontsize=14, pad=15)
plt.xlabel('Ground Truth (Valori di Riferimento)', fontsize=11)
plt.ylabel('Predizioni (Modello Random Forest)', fontsize=11)
plt.legend(fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
output_filename = "rf_calibration_performance.png"
plt.savefig(output_filename, dpi=300)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

print("--- INIZIO PIPELINE PREDITTIVA LSTM ---")

# ==========================================================================
# 0. VERIFICA DELLA COLONNA 'ts' E COSTRUZIONE DELL'INDICE TEMPORALE
# ==========================================================================
# La colonna 'ts' è in MINUTI trascorsi dall'inizio dell'acquisizione

unit_ts = 'm'

df_lstm = df_pipeline.copy()
diffs = df_lstm['ts'].diff().dropna()
print(f"Intervallo mediano tra campioni consecutivi (colonna 'ts'): {diffs.median()} minuti")
print(f"Intervallo minimo / massimo: {diffs.min()} / {diffs.max()} minuti")

df_lstm['datetime'] = pd.to_datetime(df_lstm['ts'], unit=unit_ts)
df_lstm = df_lstm.set_index('datetime').sort_index()

# ==========================================================================
# 1. DOWNSAMPLING A FINESTRE DI 15 MINUTI (aggregazione per media)
# ==========================================================================
df_resampled = df_lstm[['mq_ref']].resample('15min').mean().dropna()

print(f"\nCampioni originali (post-pulizia, Cap. 6.3): {len(df_lstm)}")
print(f"Campioni dopo il downsampling a 15 minuti: {len(df_resampled)}")

if len(df_resampled) < 50:
    print("\n*** ATTENZIONE: dopo il downsampling restano pochissimi campioni. ***")
    print("*** Verifica l'unità reale della colonna 'ts' (parametro unit_ts). ***")

# ==========================================================================
# 2. SCALING (MinMaxScaler, richiesto per le reti ricorrenti)
# ==========================================================================
scaler_lstm = MinMaxScaler(feature_range=(0, 1))
data_scaled = scaler_lstm.fit_transform(df_resampled[['mq_ref']].values)

# ==========================================================================
# 3. CREAZIONE DELLE FINESTRE TEMPORALI (Sliding Window)
# ==========================================================================
def create_sequences(data, time_steps=10):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:(i + time_steps), 0])
        y.append(data[i + time_steps, 0])
    return np.array(X), np.array(y)

time_steps = 10  # 10 campioni da 15 minuti = 150 minuti di storico
X_seq, y_seq = create_sequences(data_scaled, time_steps)

# Reshape per compatibilità tensoriale LSTM: [samples, time_steps, features]
X_seq = np.reshape(X_seq, (X_seq.shape[0], X_seq.shape[1], 1))

# ==========================================================================
# 4. DATA SPLITTING (Train 80% - Test 20%), ordine cronologico preservato
# ==========================================================================
split_idx = int(len(X_seq) * 0.8)
X_train_lstm, X_test_lstm = X_seq[:split_idx], X_seq[split_idx:]
y_train_lstm, y_test_lstm = y_seq[:split_idx], y_seq[split_idx:]

print(f"\nSequenze di Addestramento: {X_train_lstm.shape[0]}")
print(f"Sequenze di Validazione: {X_test_lstm.shape[0]}")

# ==========================================================================
# 5. ARCHITETTURA DELLA RETE NEURALE LSTM
# ==========================================================================
logging.info("Costruzione dell'architettura LSTM...")
model = Sequential()
model.add(Input(shape=(time_steps, 1)))
model.add(LSTM(units=50, return_sequences=False))
model.add(Dropout(0.2))  # Prevenzione dell'overfitting
model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_squared_error')

# ==========================================================================
# 6. ADDESTRAMENTO DEL MODELLO
# ==========================================================================
logging.info("Avvio addestramento (30 Epoche)...")
history = model.fit(X_train_lstm, y_train_lstm, epochs=30, batch_size=16,
                     validation_split=0.1, verbose=1)

# ==========================================================================
# 7. INFERENZA PREDITTIVA SUL TEST SET
# ==========================================================================
logging.info("Calcolo delle previsioni sul Test Set...")
predictions = model.predict(X_test_lstm)

# Riportiamo i dati alla scala originale (inversione del MinMaxScaler)
predictions_inverse = scaler_lstm.inverse_transform(predictions)
y_test_inverse = scaler_lstm.inverse_transform(y_test_lstm.reshape(-1, 1))

# ==========================================================================
# 8. VALUTAZIONE METROLOGICA DELLE PERFORMANCE (in scala originale)
# ==========================================================================
mae_lstm = mean_absolute_error(y_test_inverse, predictions_inverse)
rmse_lstm = np.sqrt(mean_squared_error(y_test_inverse, predictions_inverse))
r2_lstm = r2_score(y_test_inverse, predictions_inverse)

print("\n--- PERFORMANCE DEL MODELLO LSTM (TEST SET, scala originale) ---")
print(f"MAE (Errore Assoluto Medio): {mae_lstm:.2f}")
print(f"RMSE (Radice dell'Errore Quadratico Medio): {rmse_lstm:.2f}")
print(f"R^2 Score (Coefficiente di Determinazione): {r2_lstm:.4f}")

# ==========================================================================
# 9. RENDERING GRAFICO (Forecasting)
# ==========================================================================
plt.figure(figsize=(12, 6))

plt.plot(y_test_inverse, color='crimson', label='Dato Reale Calibrato (Target)', linewidth=1.5)
plt.plot(predictions_inverse, color='teal', label='Previsione LSTM (Forecasting)',
         linewidth=1.5, linestyle='--')

plt.title('Forecasting LSTM: Previsione dell\'andamento inquinante '
          f'(MAE={mae_lstm:.2f}, RMSE={rmse_lstm:.2f}, R²={r2_lstm:.3f})',
          fontsize=13, pad=15)
plt.xlabel('Finestre Temporali da 15 min (Test Set)', fontsize=11)
plt.ylabel('Concentrazione MQ135 Calibrata (Valori ADC)', fontsize=11)
plt.legend(fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
output_filename = "lstm_forecasting_performance.png"
plt.savefig(output_filename, dpi=300)
logging.info(f"Rendering completato. Immagine salvata come: {output_filename}")
plt.show()

# ==========================================================================
# 10. ESPORTAZIONE DEI MODELLI PER L'EDGE AI (Raspberry Pi)
# ==========================================================================
import joblib
import os

logging.info("Salvataggio dei modelli e degli scaler in corso...")

# Salvataggio del modello e dello scaler per la calibrazione (Random Forest)
joblib.dump(best_rf, 'model_rf.joblib')
joblib.dump(scaler, 'scaler_rf.joblib')

# Salvataggio del modello e dello scaler per il forecasting (LSTM)
model.save('model_lstm.keras')
joblib.dump(scaler_lstm, 'scaler_lstm.joblib')

logging.info("Salvataggio completato con successo. I file generati sono:")
logging.info([f for f in os.listdir('.') if f.endswith('.joblib') or f.endswith('.keras')])
print("\nI 4 file necessari per il benchmark Edge sono pronti!")